using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CliFx.Generators.SemanticModel;
using CliFx.Generators.Utils.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CliFx.Generators;

/// <summary>
/// Source generator that produces a <c>CliApplicationBuilder.AddCommandsFromThisAssembly()</c> extension method
/// that registers all source-generated command schemas from the same assembly as the caller.
/// </summary>
[Generator]
public class AddCommandsFromThisAssemblyGenerator : IIncrementalGenerator
{
    private static void Execute(
        SourceProductionContext context,
        ImmutableArray<CommandDescriptor> commandDescriptors,
        CliFxReferences cliFxRefs
    )
    {
        if (!commandDescriptors.Any())
            return;

        var publicCommands = commandDescriptors
            .Where(c => c.Type.ActualAccessibility > Accessibility.ProtectedAndInternal)
            .ToArray();

        if (!publicCommands.Any())
            return;

        var source =
            // lang=csharp
            $$"""
              // <auto-generated />
              #nullable enable

              namespace {{cliFxRefs.CliApplicationBuilder.Symbol.ContainingNamespace.ToDisplayString()}};

              /// <summary>
              /// Provides an extension method for registering all source-generated command schemas from the same assembly as the caller.
              /// </summary>
              internal static class AddCommandsFromThisAssemblyExtension
              {
                  /// <summary>
                  /// Registers all non-private source-generated command schemas from the same assembly as the caller.
                  /// </summary>
                  internal static {{cliFxRefs.CliApplicationBuilder}} AddCommandsFromThisAssembly(
                      this {{cliFxRefs.CliApplicationBuilder}} builder
                  )
                  {
                      {{string.Join(
                          Environment.NewLine,
                          publicCommands.Select(c =>
                              // lang=csharp
                              $"builder.AddCommand({c.Type}.Schema);"
                          )
                      )}}

                      return builder;
                  }
              }
              """;

        context.AddSource(
            "AddCommandsFromThisAssembly.g.cs",
            SourceText.From(source, Encoding.UTF8)
        );
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var cliFxRefs = context.CompilationProvider.Select(
            static (compilation, _) => new CliFxReferences(compilation)
        );

        var commandDeclarations = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                CliFxReferences.CommandAttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)ctx.TargetNode;
                    var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    return (ClassDeclaration: classDeclaration, Symbol: typeSymbol);
                }
            )
            .Combine(cliFxRefs)
            .Select(
                static (pair, _) =>
                {
                    var (item, cliFxRefs) = pair;
                    if (
                        !item.ClassDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword)
                        || item.Symbol.IsAbstract
                        || !item.Symbol.AllInterfaces.Any(i =>
                            SymbolEqualityComparer.Default.Equals(i, cliFxRefs.ICommand.Symbol)
                        )
                    )
                    {
                        return null;
                    }

                    return new CommandDescriptorBuilder(cliFxRefs).TryBuild(item.Symbol);
                }
            )
            .WhereNotNull();

        context.RegisterSourceOutput(
            commandDeclarations.Collect().Combine(cliFxRefs),
            static (ctx, pair) => Execute(ctx, pair.Left, pair.Right)
        );
    }
}
