using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CliFx.Generators.Binding;
using CliFx.Generators.Utils.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CliFx.Generators;

/// <summary>
/// Source generator that produces a <c>CliApplicationBuilder.AddCommandsFromThisAssembly()</c> extension method
/// that registers all source-generated command schemas from the same assembly as the caller.
/// </summary>
[Generator]
public class AddCommandsFromThisAssemblyGenerator : IIncrementalGenerator
{
    private static void Execute(
        SourceProductionContext context,
        ImmutableArray<CommandSymbol> commandSymbols,
        KnownSymbols knownSymbols
    )
    {
        if (!commandSymbols.Any())
            return;

        var publicCommands = commandSymbols
            .Where(c => c.Type.ActualAccessibility > Accessibility.ProtectedAndInternal)
            .ToArray();

        if (!publicCommands.Any())
            return;

        var source =
            // lang=csharp
            $$"""
              // <auto-generated />
              #nullable enable

              namespace {{knownSymbols.CliApplicationBuilder.Symbol.ContainingNamespace.ToDisplayString()}};

              /// <summary>
              /// Provides an extension method for registering all source-generated command descriptors from the same assembly as the caller.
              /// </summary>
              internal static class AddCommandsFromThisAssemblyExtension
              {
                  /// <summary>
                  /// Registers all non-private source-generated command descriptors from the same assembly as the caller.
                  /// </summary>
                  internal static {{knownSymbols.CliApplicationBuilder}} AddCommandsFromThisAssembly(
                      this {{knownSymbols.CliApplicationBuilder}} builder
                  )
                  {
                      {{string.Join(
                          Environment.NewLine,
                          publicCommands.Select(c =>
                              // lang=csharp
                              $"builder.AddCommand({c.Type}.Descriptor);"
                          )
                      )}}

                      return builder;
                  }
              }
              """;

        context.AddSource(
            "AddCommandsFromThisAssembly.g.cs",
            SourceText.From(source, Encoding.UTF8)
        );
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var knownSymbols = context.CompilationProvider.Select(
            static (compilation, _) => new KnownSymbols(compilation)
        );

        var commandSymbols = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                KnownSymbols.CommandAttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)ctx.TargetNode;
                    var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    return (ClassDeclaration: classDeclaration, Symbol: typeSymbol);
                }
            )
            .Combine(knownSymbols)
            .Select(
                static (pair, _) =>
                {
                    var (item, knownSymbols) = pair;
                    if (!item.ClassDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
                    {
                        return null;
                    }

                    return CommandSymbol.TryResolve(
                        item.Symbol,
                        knownSymbols,
                        out var commandDiagnostics
                    );
                }
            )
            .WhereNotNull();

        context.RegisterSourceOutput(
            commandSymbols.Collect().Combine(knownSymbols),
            static (ctx, pair) => Execute(ctx, pair.Left, pair.Right)
        );
    }
}
