using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CliFx.SourceGeneration.SemanticModel;
using CliFx.SourceGeneration.Utils.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CliFx.SourceGeneration;

/// <summary>
/// Source generator that produces a <c>CliApplicationBuilder.AddCommandsFromThisAssembly()</c> extension method
/// that registers all source-generated command schemas from the same assembly as the caller.
/// </summary>
[Generator]
public class AddCommandsFromThisAssemblyGenerator : IIncrementalGenerator
{
    private static void Execute(
        SourceProductionContext context,
        ImmutableArray<CommandDescriptor> commandDescriptors
    )
    {
        if (!commandDescriptors.Any())
            return;

        var publicCommands = commandDescriptors
            .Where(c => c.Type.ActualAccessibility > Accessibility.ProtectedAndInternal)
            .ToArray();

        if (!publicCommands.Any())
            return;

        var source =
            // lang=csharp
            $$"""
              // <auto-generated/>
              #nullable enable

              namespace CliFx;

              /// <summary>
              /// Provides an extension method for registering all source-generated command schemas from the same assembly as the caller.
              /// </summary>
              internal static class AddCommandsFromThisAssemblyExtension
              {
                  /// <summary>
                  /// Registers all non-private source-generated command schemas from the same assembly as the caller.
                  /// </summary>
                  internal static global::CliFx.CliApplicationBuilder AddCommandsFromThisAssembly(
                      this global::CliFx.CliApplicationBuilder builder
                  )
                  {
                      {{string.Join(
                          Environment.NewLine,
                          publicCommands.Select(c =>
                              // lang=csharp
                              $"builder.AddCommand({c.Type}.Schema);"
                          )
                      )}}

                      return builder;
                  }
              }
              """;

        context.AddSource(
            "AddCommandsFromThisAssembly.g.cs",
            SourceText.From(source, Encoding.UTF8)
        );
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandDeclarations = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                SymbolNames.CliFxCommandAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)ctx.TargetNode;
                    var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

                    if (
                        !classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword)
                        || typeSymbol.IsAbstract
                        || !typeSymbol.ImplementsInterface(SymbolNames.CliFxCommandInterface)
                    )
                        return null;

                    return CommandSchemaGenerator.TryBuildCommandDescriptor(typeSymbol);
                }
            )
            .WhereNotNull();

        context.RegisterSourceOutput(
            commandDeclarations.Collect(),
            static (ctx, commands) => Execute(ctx, commands)
        );
    }
}
