namespace CliFx.Generators;

public partial class Generator
{
    private static string EmitProgramEntryPoint()
    {
        // lang=csharp
        return """
            // <auto-generated />
            #nullable enable

            namespace CliFx;

            public static class Program
            {
                public static async global::System.Threading.Tasks.Task<int> Main() =>
                    await new global::CliFx.CommandLineApplicationBuilder()
                        .AddCommandsFromThisAssembly()
                        .Build()
                        .RunAsync();
            }
            """;
    }
}
