using System.Collections.Generic;
using System.Linq;
using System.Text;
using CliFx.Generators.Binding;
using CliFx.Generators.Utils;
using CliFx.Generators.Utils.Extensions;
using Microsoft.CodeAnalysis;

namespace CliFx.Generators;

public partial class Generator
{
    private static string EmitCommandDescriptor(
        CommandSymbol command,
        out IReadOnlyList<Diagnostic> diagnostics
    )
    {
        var namespaceName = command.Type.TryGetNamespaceName();
        var commandTypeName = command.Type.Name;
        var commandTypeFqn = command.Type.GetGloballyQualifiedName();

        var interfaces = new List<string>(2) { "global::" + KnownTypes.ICommandWithHelpOption };
        if (command.IsDefault)
            interfaces.Add("global::" + KnownTypes.ICommandWithVersionOption);

        var interfaceList =
            interfaces.Count > 0 ? " : " + string.Join(", ", interfaces) : string.Empty;

        var sb = new StringBuilder();

        sb.Append(
            """
            // <auto-generated />

            """
        );

        if (namespaceName is not null)
        {
            sb.Append(
                $$"""
                namespace {{namespaceName}};

                """
            );
        }

        foreach (var containingType in command.Type.GetContainingTypes().Reverse())
        {
            sb.AppendLine(
                $"partial class {containingType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}"
            );
            sb.AppendLine("{");
        }

        sb.Append(
            $$"""
            partial class {{commandTypeName}}{{interfaceList}}
            {
            """
        );

        sb.Append(
            """

                /// <inheritdoc />
                public bool IsHelpRequested { get; set; }

            """
        );

        if (command.IsDefault)
        {
            sb.Append(
                """

                    /// <inheritdoc />
                    public bool IsVersionRequested { get; set; }

                """
            );
        }

        sb.Append(
            $$"""

                /// <summary>Generated command descriptor for <see cref="{{commandTypeName}}"/>.</summary>
                public static global::{{KnownTypes.CommandDescriptor}} Descriptor { get; } =
                    new global::{{KnownTypes.CommandDescriptor}}<{{commandTypeFqn}}>(
                        {{CSharp.Encode(command.Name)}},
                        {{CSharp.Encode(command.Description)}},
                        new global::{{KnownTypes.CommandInputDescriptor}}[]
                        {
            """
        );

        var diagnosticsList = new List<Diagnostic>();

        foreach (var param in command.Parameters.OrderBy(p => p.Order))
        {
            var converterExpr = TryBuildConverterExpr(
                param.ConverterType,
                param.Property,
                param.IsElementConverter
            );
            if (converterExpr is null)
            {
                diagnosticsList.Add(
                    Diagnostic.Create(
                        DiagnosticDescriptors.CommandInputConverterNotInferrable,
                        param.Property.Locations.FirstOrDefault(),
                        param.Property.Name,
                        param.Property.Type.GetGloballyQualifiedName()
                    )
                );
                continue;
            }

            var propTypeFqn = param.Property.Type.GetGloballyQualifiedName();

            sb.Append(
                // lang=csharp
                $$"""
                            new global::{{KnownTypes.CommandParameterDescriptor}}<{{commandTypeFqn}}, {{propTypeFqn}}>(
                                new global::{{KnownTypes.PropertyDescriptor}}<{{commandTypeFqn}}, {{propTypeFqn}}>(
                                    "{{param.Property.Name}}",
                                    c => c.{{param.Property.Name}},
                                    (c, v) => c.{{param.Property.Name}} = v),
                                {{param.Order}},
                                {{CSharp.Encode(param.Name)}},
                                {{(param.IsRequired ? "true" : "false")}},
                                {{CSharp.Encode(param.Description)}},
                                {{converterExpr}},
                                {{BuildValidatorsExpr(param.ValidatorTypes, propTypeFqn)}}),
                """
            );
        }

        foreach (var option in command.Options)
        {
            var converterExpr = TryBuildConverterExpr(
                option.ConverterType,
                option.Property,
                option.IsElementConverter
            );
            if (converterExpr is null)
            {
                diagnosticsList.Add(
                    Diagnostic.Create(
                        DiagnosticDescriptors.CommandInputConverterNotInferrable,
                        option.Property.Locations.FirstOrDefault(),
                        option.Property.Name,
                        option.Property.Type.GetGloballyQualifiedName()
                    )
                );
                continue;
            }

            var propTypeFqn = option.Property.Type.GetGloballyQualifiedName();

            sb.Append(
                // lang=csharp
                $$"""
                            new global::{{KnownTypes.CommandOptionDescriptor}}<{{commandTypeFqn}}, {{propTypeFqn}}>(
                                new global::{{KnownTypes.PropertyDescriptor}}<{{commandTypeFqn}}, {{propTypeFqn}}>(
                                    "{{option.Property.Name}}",
                                    c => c.{{option.Property.Name}},
                                    (c, v) => c.{{option.Property.Name}} = v),
                                {{CSharp.Encode(option.Name)}},
                                {{(option.ShortName.HasValue ? $"'{option.ShortName}'" : "null")}},
                                {{CSharp.Encode(option.EnvironmentVariable)}},
                                {{(option.IsRequired ? "true" : "false")}},
                                {{CSharp.Encode(option.Description)}},
                                {{converterExpr}},
                                {{BuildValidatorsExpr(option.ValidatorTypes, propTypeFqn)}}),

                """
            );
        }

        EmitBuiltInHelpOption(sb, command, diagnosticsList);

        if (command.IsDefault)
            EmitBuiltInVersionOption(sb, command, diagnosticsList);

        sb.Append(
            """
                        });
                }
            """
        );

        foreach (var _ in command.Type.GetContainingTypes())
        {
            sb.AppendLine();
            sb.AppendLine("}");
        }

        diagnostics = diagnosticsList;
        return sb.ToString();
    }

    private static void EmitBuiltInHelpOption(
        StringBuilder sb,
        CommandSymbol command,
        List<Diagnostic> diagnostics
    )
    {
        var commandTypeFqn = command.Type.GetGloballyQualifiedName();

        var helpOptionByShortName = command.Options.FirstOrDefault(o => o.ShortName == 'h');
        var helpOptionByName = command.Options.FirstOrDefault(o =>
            string.Equals(o.Name, "help", System.StringComparison.OrdinalIgnoreCase)
        );

        var includeBuiltInHelpShortName = helpOptionByShortName is null;
        var includeBuiltInHelpName = helpOptionByName is null;
        var shouldEmitBuiltInHelpOption = includeBuiltInHelpShortName && includeBuiltInHelpName;

        if (helpOptionByShortName is not null || helpOptionByName is not null)
        {
            var option = helpOptionByShortName ?? helpOptionByName;
            var shadowedIdentifier = helpOptionByShortName is not null ? "-h" : "--help";

            diagnostics.Add(
                Diagnostic.Create(
                    DiagnosticDescriptors.CommandOptionShadowsBuiltInHelpOption,
                    option?.Property.Locations.FirstOrDefault(),
                    option?.Property.Name,
                    shadowedIdentifier
                )
            );
        }

        if (shouldEmitBuiltInHelpOption)
        {
            sb.Append(
                // lang=csharp
                $$"""
                            new global::{{KnownTypes.CommandOptionDescriptor}}<{{commandTypeFqn}}, bool>(
                                new global::{{KnownTypes.PropertyDescriptor}}<{{commandTypeFqn}}, bool>(
                                    "IsHelpRequested",
                                    c => c.IsHelpRequested,
                                    (c, v) => c.IsHelpRequested = v),
                                {{(includeBuiltInHelpName ? "\"help\"" : "null")}},
                                {{(includeBuiltInHelpShortName ? "'h'" : "null")}},
                                null,
                                false,
                                "Shows help text.",
                                new global::{{KnownTypes.BoolScalarInputConverter}}(),
                                global::System.Array.Empty<global::{{KnownTypes.InputValidator}}<bool>>()),

                """
            );
        }
    }

    private static void EmitBuiltInVersionOption(
        StringBuilder sb,
        CommandSymbol command,
        List<Diagnostic> diagnostics
    )
    {
        var commandTypeFqn = command.Type.GetGloballyQualifiedName();

        var versionOptionByName = command.Options.FirstOrDefault(o =>
            string.Equals(o.Name, "version", System.StringComparison.OrdinalIgnoreCase)
        );

        var shouldEmitBuiltInVersionOption = versionOptionByName is null;

        if (versionOptionByName is not null)
        {
            diagnostics.Add(
                Diagnostic.Create(
                    DiagnosticDescriptors.CommandOptionShadowsBuiltInVersionOption,
                    versionOptionByName.Property.Locations.FirstOrDefault(),
                    versionOptionByName.Property.Name,
                    "--version"
                )
            );
        }

        if (shouldEmitBuiltInVersionOption)
        {
            sb.Append(
                // lang=csharp
                $$"""
                            new global::{{KnownTypes.CommandOptionDescriptor}}<{{commandTypeFqn}}, bool>(
                                new global::{{KnownTypes.PropertyDescriptor}}<{{commandTypeFqn}}, bool>(
                                    "IsVersionRequested",
                                    c => c.IsVersionRequested,
                                    (c, v) => c.IsVersionRequested = v),
                                "version",
                                null,
                                null,
                                false,
                                "Shows version information.",
                                new global::{{KnownTypes.BoolScalarInputConverter}}(),
                                global::System.Array.Empty<global::{{KnownTypes.InputValidator}}<bool>>()),

                """
            );
        }
    }

    private static string? TryBuildConverterExpr(
        INamedTypeSymbol? userConverterType,
        IPropertySymbol property,
        bool isElementConverter
    )
    {
        if (userConverterType is not null)
        {
            var userConverterExpr = $"new {userConverterType.GetGloballyQualifiedName()}()";

            if (isElementConverter)
            {
                // The user provided a scalar element converter that needs to be wrapped
                // in an appropriate sequence converter
                var collectionType = property.Type;
                if (
                    collectionType.SpecialType != SpecialType.System_String
                    && collectionType.TryGetEnumerableUnderlyingType() is { } underlyingType
                )
                {
                    return TryBuildSequenceConverterExpr(
                        underlyingType,
                        collectionType,
                        userConverterExpr
                    );
                }
            }

            return userConverterExpr;
        }

        var type = property.Type;

        if (
            type.SpecialType != SpecialType.System_String
            && type.TryGetEnumerableUnderlyingType() is { } elementType
        )
        {
            var elementConverterExpr = TryBuildDefaultScalarConverterExpr(elementType);
            if (elementConverterExpr is null)
                return null;

            return TryBuildSequenceConverterExpr(elementType, type, elementConverterExpr);
        }

        return TryBuildDefaultScalarConverterExpr(type);
    }

    private static string? TryBuildDefaultScalarConverterExpr(ITypeSymbol type)
    {
        var typeFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Object
        if (type.SpecialType == SpecialType.System_Object)
            return $"new global::{KnownTypes.StringScalarInputConverter}()";

        // String
        if (type.SpecialType == SpecialType.System_String)
            return $"new global::{KnownTypes.StringScalarInputConverter}()";

        // Bool
        if (type.SpecialType == SpecialType.System_Boolean)
            return $"new global::{KnownTypes.BoolScalarInputConverter}()";

        // Enum
        if (type.TypeKind == TypeKind.Enum)
            return $"new global::{KnownTypes.EnumScalarInputConverter}<{typeFqn}>()";

        // Nullable<T>
        if (
            type is INamedTypeSymbol { IsValueType: true } named
            && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T
        )
        {
            var innerType = named.TypeArguments[0];
            var innerFqn = innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var innerConverterExpr = TryBuildDefaultScalarConverterExpr(innerType);
            if (innerConverterExpr is null)
                return null;
            return $"new global::{KnownTypes.NullableScalarInputConverter}<{innerFqn}>({innerConverterExpr})";
        }

        // Has static Parse(string, IFormatProvider)
        var parseMethodWithFormatProvider = type.GetMembers("Parse")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsStatic
                && m.DeclaredAccessibility == Accessibility.Public
                && m.Parameters.Length == 2
                && m.Parameters[0].Type.SpecialType == SpecialType.System_String
                && m.Parameters[1].Type
                    is { ContainingNamespace.Name: "System", Name: "IFormatProvider" }
                && SymbolEqualityComparer.Default.Equals(m.ReturnType, type)
            );

        if (parseMethodWithFormatProvider is not null)
            return $"new global::{KnownTypes.DelegateScalarInputConverter}<{typeFqn}>(s => {typeFqn}.Parse(s!, global::System.Globalization.CultureInfo.InvariantCulture))";

        // Has static Parse(string)
        var parseMethod = type.GetMembers("Parse")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsStatic
                && m.DeclaredAccessibility == Accessibility.Public
                && m.Parameters.Length == 1
                && m.Parameters[0].Type.SpecialType == SpecialType.System_String
                && SymbolEqualityComparer.Default.Equals(m.ReturnType, type)
            );

        if (parseMethod is not null)
            return $"new global::{KnownTypes.DelegateScalarInputConverter}<{typeFqn}>(s => {typeFqn}.Parse(s!))";

        // Has ctor(string)
        if (
            type is INamedTypeSymbol namedConstructable
            && namedConstructable.Constructors.Any(c =>
                c.DeclaredAccessibility == Accessibility.Public
                && c.Parameters.Length == 1
                && c.Parameters[0].Type.SpecialType == SpecialType.System_String
            )
        )
        {
            return $"new global::{KnownTypes.DelegateScalarInputConverter}<{typeFqn}>(s => new {typeFqn}(s!))";
        }

        // Implements IConvertible
        if (
            type.AllInterfaces.Any(i =>
                i.ContainingNamespace?.Name == "System" && i.Name == "IConvertible"
            )
        )
        {
            return $"new global::{KnownTypes.ConvertibleScalarInputConverter}<{typeFqn}>()";
        }

        return null;
    }

    private static string? TryBuildSequenceConverterExpr(
        ITypeSymbol elementType,
        ITypeSymbol collectionType,
        string elementConverterExpr
    )
    {
        var collectionTypeFqn = collectionType.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat
        );
        var elementTypeFqn = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // T[] or IEnumerable<T> or ICollection<T> or IList<T> or IReadOnlyCollection<T> or IReadOnlyList<T>
        if (
            collectionType is IArrayTypeSymbol
            || (
                collectionType
                    is INamedTypeSymbol
                    {
                        TypeKind: TypeKind.Interface,
                        TypeArguments: [var interfaceElementType],
                    } namedInterface
                && SymbolEqualityComparer.Default.Equals(interfaceElementType, elementType)
                && namedInterface.ConstructedFrom.SpecialType
                    is SpecialType.System_Collections_Generic_IEnumerable_T
                        or SpecialType.System_Collections_Generic_ICollection_T
                        or SpecialType.System_Collections_Generic_IList_T
                        or SpecialType.System_Collections_Generic_IReadOnlyCollection_T
                        or SpecialType.System_Collections_Generic_IReadOnlyList_T
            )
        )
            return $"new global::{KnownTypes.ArraySequenceInputConverter}<{elementTypeFqn}>({elementConverterExpr})";

        // Has ctor(string[])
        if (
            collectionType is INamedTypeSymbol namedCollection
            && namedCollection.Constructors.Any(c =>
                c.DeclaredAccessibility == Accessibility.Public
                && c.Parameters.Length == 1
                && (
                    (
                        c.Parameters[0].Type is IArrayTypeSymbol arrParam
                        && SymbolEqualityComparer.Default.Equals(arrParam.ElementType, elementType)
                    )
                    || (
                        c.Parameters[0].Type is INamedTypeSymbol paramType
                        && paramType.ConstructedFrom.SpecialType
                            == SpecialType.System_Collections_Generic_IEnumerable_T
                        && SymbolEqualityComparer.Default.Equals(
                            paramType.TypeArguments[0],
                            elementType
                        )
                    )
                )
            )
        )
        {
            return $"new global::{KnownTypes.DelegateSequenceInputConverter}<{elementTypeFqn}[], {collectionTypeFqn}>(new global::{KnownTypes.ArraySequenceInputConverter}<{elementTypeFqn}>({elementConverterExpr}), values => new {collectionTypeFqn}(values))";
        }

        return null;
    }

    private static string BuildValidatorsExpr(
        IReadOnlyList<INamedTypeSymbol> validatorTypes,
        string propertyTypeFqn
    )
    {
        var validatorBaseType = $"global::{KnownTypes.InputValidator}<{propertyTypeFqn}>";

        if (validatorTypes.Count == 0)
            return $"global::System.Array.Empty<{validatorBaseType}>()";

        var items = string.Join(
            ", ",
            validatorTypes.Select(v => $"new {v.GetGloballyQualifiedName()}()")
        );
        return $"new {validatorBaseType}[] {{ {items} }}";
    }
}
