using System;
using System.Collections.Generic;
using System.Linq;
using CliFx.Generators.Binding;
using CliFx.Generators.Utils;
using CliFx.Generators.Utils.Extensions;
using Microsoft.CodeAnalysis;

namespace CliFx.Generators;

internal static class CommandRegistrationEmitter
{
    internal static string Emit(IReadOnlyList<CommandSymbol> commands)
    {
        var orderedCommands = commands.OrderBy(c => c.Name, StringComparer.Ordinal).ToArray();

        // lang=csharp
        return $$"""
                // <auto-generated />
                #nullable enable

                namespace CliFx;

                /// <summary>
                /// Provides an extension method for registering all accessible source-generated commands from the same assembly as the caller.
                /// </summary>
                internal static class CommandRegistrations
                {
                    /// <summary>
                    /// Registers all accessible source-generated commands from the same assembly as the caller.
                    /// </summary>
                    /// <remarks>
                    /// <list type="bullet">
                        {{string.Join(
                            Environment.NewLine,
                            orderedCommands.Select(c =>
                                $"""
                                /// <item>
                                /// <see cref="{Xml.Escape(c.Type.GetGloballyQualifiedName())}" /> ({Xml.Escape(c.ToString())})
                                /// </item>
                                """
                            )
                        ).NullIfWhiteSpace() ?? "///"}}
                    /// </list>
                    /// </remarks>
                    internal static global::CliFx.CommandLineApplicationBuilder AddCommandsFromThisAssembly(
                        this global::CliFx.CommandLineApplicationBuilder builder
                    )
                    {
                        {{string.Join(
                            Environment.NewLine,
                            orderedCommands.Select(c =>
                                // lang=csharp
                                $"builder.AddCommand({c.Type.GetGloballyQualifiedName()}.Descriptor);"
                            )
                        )}}

                        return builder;
                    }
                }
                """;
    }
}
