using System.Collections.Generic;
using System.Linq;
using System.Text;
using CliFx.Generators.Binding;
using CliFx.Generators.Utils.Extensions;
using Microsoft.CodeAnalysis;

namespace CliFx.Generators;

public partial class Generator
{
    private static string EmitCommandDescriptor(
        CommandSymbol command,
        out IReadOnlyList<Diagnostic> diagnostics
    )
    {
        var namespaceName = command.Type.Namespace;

        var interfaces = new List<string>(2) { KnownSymbols.ICommandWithHelpOption.ToString() };
        if (command.IsDefault)
            interfaces.Add(KnownSymbols.ICommandWithVersionOption.ToString());

        var interfaceList =
            interfaces.Count > 0 ? " : " + string.Join(", ", interfaces) : string.Empty;

        var sb = new StringBuilder();

        sb.Append(
            """
            // <auto-generated />

            """
        );

        if (namespaceName is not null)
        {
            sb.Append(
                $$"""
                namespace {{namespaceName}};

                """
            );
        }

        foreach (var containingType in command.Type.Symbol.GetContainingTypes().Reverse())
        {
            sb.AppendLine(
                $"partial class {containingType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}"
            );
            sb.AppendLine("{");
        }

        sb.Append(
            $$"""
            partial class {{command.Type.Name}}{{interfaceList}}
            {
            """
        );

        sb.Append(
            """

                /// <inheritdoc />
                public bool IsHelpRequested { get; set; }

            """
        );

        if (command.IsDefault)
        {
            sb.Append(
                """

                    /// <inheritdoc />
                    public bool IsVersionRequested { get; set; }

                """
            );
        }

        sb.Append(
            $$"""

                /// <summary>Generated command descriptor for <see cref="{{command.Type.Name}}"/>.</summary>
                public static {{KnownSymbols.CommandDescriptor}} Descriptor { get; } =
                    new {{KnownSymbols.CommandDescriptor}}<{{command.Type.FullyQualifiedName}}>(
                        {{EncodeString(command.Name)}},
                        {{EncodeString(command.Description)}},
                        new {{KnownSymbols.CommandInputDescriptor}}[]
                        {
            """
        );

        var diagnosticsList = new List<Diagnostic>();

        foreach (var param in command.Parameters.OrderBy(p => p.Order))
        {
            var converterExpr = TryBuildConverterExpr(param.ConverterType, param.Property);
            if (converterExpr is null)
            {
                diagnosticsList.Add(
                    Diagnostic.Create(
                        DiagnosticDescriptors.ConverterNotInferrable,
                        param.Property.Locations.FirstOrDefault() ?? Location.None,
                        param.Property.Name,
                        TypeIdentifier.From(param.Property.Type).FullyQualifiedName
                    )
                );
                continue;
            }

            sb.Append(
                // lang=csharp
                $$"""
                            new {{KnownSymbols.CommandParameterDescriptor}}<{{command.Type.FullyQualifiedName}}, {{TypeIdentifier.From(param.Property.Type).FullyQualifiedName}}>(
                                new {{KnownSymbols.PropertyDescriptor}}<{{command.Type.FullyQualifiedName}}, {{TypeIdentifier.From(param.Property.Type).FullyQualifiedName}}>(
                                    "{{param.Property.Name}}",
                                    c => c.{{param.Property.Name}},
                                    (c, v) => c.{{param.Property.Name}} = v),
                                {{param.Order}},
                                {{EncodeString(param.Name)}},
                                {{(param.IsRequired ? "true" : "false")}},
                                {{EncodeString(param.Description)}},
                                {{converterExpr}},
                                {{BuildValidatorsExpr(
                    param.ValidatorTypes,
                    TypeIdentifier.From(param.Property.Type).FullyQualifiedName)}}),
                """
            );
        }

        foreach (var option in command.Options)
        {
            var converterExpr = TryBuildConverterExpr(option.ConverterType, option.Property);
            if (converterExpr is null)
            {
                diagnosticsList.Add(
                    Diagnostic.Create(
                        DiagnosticDescriptors.ConverterNotInferrable,
                        option.Property.Locations.FirstOrDefault() ?? Location.None,
                        option.Property.Name,
                        TypeIdentifier.From(option.Property.Type).FullyQualifiedName
                    )
                );
                continue;
            }

            sb.Append(
                // lang=csharp
                $$"""
                            new {{KnownSymbols.CommandOptionDescriptor}}<{{command.Type.FullyQualifiedName}}, {{TypeIdentifier.From(option.Property.Type).FullyQualifiedName}}>(
                                new {{KnownSymbols.PropertyDescriptor}}<{{command.Type.FullyQualifiedName}}, {{TypeIdentifier.From(option.Property.Type).FullyQualifiedName}}>(
                                    "{{option.Property.Name}}",
                                    c => c.{{option.Property.Name}},
                                    (c, v) => c.{{option.Property.Name}} = v),
                                {{EncodeString(option.Name)}},
                                {{(option.ShortName.HasValue ? $"'{option.ShortName}'" : "null")}},
                                {{EncodeString(option.EnvironmentVariable)}},
                                {{(option.IsRequired ? "true" : "false")}},
                                {{EncodeString(option.Description)}},
                                {{converterExpr}},
                                {{BuildValidatorsExpr(
                    option.ValidatorTypes,
                    TypeIdentifier.From(option.Property.Type).FullyQualifiedName
                )}}),

                """
            );
        }

        sb.Append(
            // lang=csharp
            $$"""
                        new {{KnownSymbols.CommandOptionDescriptor}}<{{command.Type.FullyQualifiedName}}, bool>(
                            new {{KnownSymbols.PropertyDescriptor}}<{{command.Type.FullyQualifiedName}}, bool>(
                                "IsHelpRequested",
                                c => c.IsHelpRequested,
                                (c, v) => c.IsHelpRequested = v),
                            "help",
                            'h',
                            null,
                            false,
                            "Shows help text.",
                            new {{KnownSymbols.BoolScalarInputConverter}}(),
                            global::System.Array.Empty<{{KnownSymbols.InputValidator.GlobalFullyQualifiedName}}<bool>>()),

            """
        );

        if (command.IsDefault)
            sb.Append(
                // lang=csharp
                $$"""
                            new {{KnownSymbols.CommandOptionDescriptor}}<{{command.Type.FullyQualifiedName}}, bool>(
                                new {{KnownSymbols.PropertyDescriptor}}<{{command.Type.FullyQualifiedName}}, bool>(
                                    "IsVersionRequested",
                                    c => c.IsVersionRequested,
                                    (c, v) => c.IsVersionRequested = v),
                                "version",
                                null,
                                null,
                                false,
                                "Shows version information.",
                                new {{KnownSymbols.BoolScalarInputConverter}}(),
                                global::System.Array.Empty<{{KnownSymbols.InputValidator.GlobalFullyQualifiedName}}<bool>>()),

                """
            );

        sb.Append(
            """
                        });
                }
            """
        );

        foreach (var _ in command.Type.Symbol.GetContainingTypes())
        {
            sb.AppendLine();
            sb.AppendLine("}");
        }

        diagnostics = diagnosticsList;
        return sb.ToString();
    }

    private static string? TryBuildConverterExpr(
        TypeIdentifier? userConverterType,
        IPropertySymbol property
    )
    {
        if (userConverterType is not null)
            return $"new {userConverterType.GlobalFullyQualifiedName}()";

        var type = property.Type;

        if (
            type.SpecialType != SpecialType.System_String
            && type.TryGetEnumerableUnderlyingType() is { } elementType
        )
            return TryBuildDefaultSequenceConverterExpr(elementType, type);

        return TryBuildDefaultScalarConverterExpr(type);
    }

    private static string? TryBuildDefaultScalarConverterExpr(ITypeSymbol type)
    {
        var typeFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (type.SpecialType == SpecialType.System_String)
            return $"new {KnownSymbols.StringScalarInputConverter}()";

        if (type.SpecialType == SpecialType.System_Object)
            return $"new {KnownSymbols.ObjectScalarInputConverter}()";

        if (type.SpecialType == SpecialType.System_Boolean)
            return $"new {KnownSymbols.BoolScalarInputConverter}()";

        if (type is INamedTypeSymbol { ContainingNamespace.Name: "System", Name: "DateTimeOffset" })
            return $"new {KnownSymbols.DateTimeOffsetScalarInputConverter}()";

        if (type is INamedTypeSymbol { ContainingNamespace.Name: "System", Name: "DateTime" })
            return $"new {KnownSymbols.DateTimeScalarInputConverter}()";

        if (type is INamedTypeSymbol { ContainingNamespace.Name: "System", Name: "TimeSpan" })
            return $"new {KnownSymbols.TimeSpanScalarInputConverter}()";

        if (type.TypeKind == TypeKind.Enum)
            return $"new {KnownSymbols.EnumScalarInputConverter.GlobalFullyQualifiedName}<{typeFqn}>()";

        if (
            type is INamedTypeSymbol { IsValueType: true } named
            && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T
        )
        {
            var innerType = named.TypeArguments[0];
            var innerFqn = innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var innerConverterExpr = TryBuildDefaultScalarConverterExpr(innerType);
            if (innerConverterExpr is null)
                return null;
            return $"new {KnownSymbols.NullableScalarInputConverter.GlobalFullyQualifiedName}<{innerFqn}>({innerConverterExpr})";
        }

        var parseMethodWithFormatProvider = type.GetMembers("Parse")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsStatic
                && m.DeclaredAccessibility == Accessibility.Public
                && m.Parameters.Length == 2
                && m.Parameters[0].Type.SpecialType == SpecialType.System_String
                && m.Parameters[1].Type
                    is { ContainingNamespace.Name: "System", Name: "IFormatProvider" }
                && SymbolEqualityComparer.Default.Equals(m.ReturnType, type)
            );

        if (parseMethodWithFormatProvider is not null)
            return $"new {KnownSymbols.DelegateScalarInputConverter.GlobalFullyQualifiedName}<{typeFqn}>(s => {typeFqn}.Parse(s!, global::System.Globalization.CultureInfo.InvariantCulture))";

        var parseMethod = type.GetMembers("Parse")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsStatic
                && m.DeclaredAccessibility == Accessibility.Public
                && m.Parameters.Length == 1
                && m.Parameters[0].Type.SpecialType == SpecialType.System_String
                && SymbolEqualityComparer.Default.Equals(m.ReturnType, type)
            );

        if (parseMethod is not null)
            return $"new {KnownSymbols.DelegateScalarInputConverter.GlobalFullyQualifiedName}<{typeFqn}>(s => {typeFqn}.Parse(s!))";

        if (
            type is INamedTypeSymbol namedConstructable
            && namedConstructable.Constructors.Any(c =>
                c.DeclaredAccessibility == Accessibility.Public
                && c.Parameters.Length == 1
                && c.Parameters[0].Type.SpecialType == SpecialType.System_String
            )
        )
        {
            return $"new {KnownSymbols.DelegateScalarInputConverter.GlobalFullyQualifiedName}<{typeFqn}>(s => new {typeFqn}(s!))";
        }

        if (
            type.AllInterfaces.Any(i =>
                i.ContainingNamespace?.Name == "System" && i.Name == "IConvertible"
            )
        )
        {
            return $"new {KnownSymbols.ConvertibleScalarInputConverter.GlobalFullyQualifiedName}<{typeFqn}>()";
        }

        return null;
    }

    private static string? TryBuildDefaultSequenceConverterExpr(
        ITypeSymbol elementType,
        ITypeSymbol collectionType
    )
    {
        var collectionTypeFqn = collectionType.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat
        );
        var elementTypeFqn = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var elementConverterArg = TryBuildDefaultScalarConverterExpr(elementType);
        if (elementConverterArg is null)
            return null;

        if (collectionType is IArrayTypeSymbol)
            return $"new {KnownSymbols.ArraySequenceInputConverter.GlobalFullyQualifiedName}<{elementTypeFqn}>({elementConverterArg})";

        if (collectionType.TypeKind == TypeKind.Interface)
            return $"new {KnownSymbols.ArraySequenceInputConverter.GlobalFullyQualifiedName}<{elementTypeFqn}, {collectionTypeFqn}>({elementConverterArg})";

        if (
            collectionType is INamedTypeSymbol namedCollection
            && namedCollection.Constructors.Any(c =>
                c.DeclaredAccessibility == Accessibility.Public
                && c.Parameters.Length == 1
                && (
                    (
                        c.Parameters[0].Type is IArrayTypeSymbol arrParam
                        && SymbolEqualityComparer.Default.Equals(arrParam.ElementType, elementType)
                    )
                    || (
                        c.Parameters[0].Type is INamedTypeSymbol paramType
                        && paramType.ConstructedFrom.SpecialType
                            == SpecialType.System_Collections_Generic_IEnumerable_T
                        && SymbolEqualityComparer.Default.Equals(
                            paramType.TypeArguments[0],
                            elementType
                        )
                    )
                )
            )
        )
        {
            return $"new {KnownSymbols.DelegateSequenceInputConverter.GlobalFullyQualifiedName}<{collectionTypeFqn}>(rawValues => new {collectionTypeFqn}(new {KnownSymbols.ArraySequenceInputConverter.GlobalFullyQualifiedName}<{elementTypeFqn}>({elementConverterArg}).Convert(rawValues)))";
        }

        return null;
    }

    private static string BuildValidatorsExpr(
        IReadOnlyList<TypeIdentifier> validatorTypes,
        string propertyTypeFqn
    )
    {
        var validatorBaseType =
            $"{KnownSymbols.InputValidator.GlobalFullyQualifiedName}<{propertyTypeFqn}>";

        if (validatorTypes.Count == 0)
            return $"global::System.Array.Empty<{validatorBaseType}>()";

        var items = string.Join(
            ", ",
            validatorTypes.Select(v => $"new {v.GlobalFullyQualifiedName}()")
        );
        return $"new {validatorBaseType}[] {{ {items} }}";
    }

    private static string EncodeString(string? value) =>
        value is null ? "null" : $"\"{value.Replace("\\", @"\\").Replace("\"", "\\\"")}\"";
}
