using System;
using System.Collections.Immutable;
using System.Linq;
using CliFx.Generators.Binding;
using Microsoft.CodeAnalysis;

namespace CliFx.Generators;

public partial class Generator
{
    private static string EmitCommandRegistrations(ImmutableArray<CommandSymbol> commands)
    {
        return
        // lang=csharp
        $$"""
            // <auto-generated />
            #nullable enable

            namespace {{KnownSymbols.CliApplicationBuilder.Namespace}};

            /// <summary>
            /// Provides an extension method for registering all source-generated commands from the same assembly as the caller.
            /// </summary>
            internal static class CommandRegistrations
            {
                /// <summary>
                /// Registers all non-private source-generated commands from the same assembly as the caller.
                /// </summary>
                internal static {{KnownSymbols.CliApplicationBuilder}} AddCommandsFromThisAssembly(
                    this {{KnownSymbols.CliApplicationBuilder}} builder
                )
                {
                    {{string.Join(
                        Environment.NewLine,
                        commands.Select(c =>
                            // lang=csharp
                            $"builder.AddCommand({c.Type}.Descriptor);"
                        )
                    )}}

                    return builder;
                }
            }
            """;
    }
}
