using System;
using System.Collections.Immutable;
using System.Linq;
using CliFx.Generators.Binding;
using CliFx.Generators.Utils.Extensions;
using Microsoft.CodeAnalysis;

namespace CliFx.Generators;

public partial class Generator
{
    private static string EmitCommandRegistrations(ImmutableArray<CommandSymbol> commands)
    {
        return
        // lang=csharp
        $$"""
            // <auto-generated />
            #nullable enable

            namespace {{KnownTypes.CommandLineApplicationBuilderNamespace}};

            /// <summary>
            /// Provides an extension method for registering all source-generated commands from the same assembly as the caller.
            /// </summary>
            internal static class CommandRegistrations
            {
                /// <summary>
                /// Registers all non-private source-generated commands from the same assembly as the caller.
                /// </summary>
                /// <remarks>
                /// <list type="bullet">
                {{string.Join(
                    Environment.NewLine,
                    commands.Select(c =>
                        $"/// <item><see cref=\"{c.Type.GetGloballyQualifiedName()}\" /></item>"
                    )
                )}}
                /// </list>
                /// </remarks>
                internal static global::{{KnownTypes.CommandLineApplicationBuilder}} AddCommandsFromThisAssembly(
                    this global::{{KnownTypes.CommandLineApplicationBuilder}} builder
                )
                {
                    {{string.Join(
                        Environment.NewLine,
                        commands.Select(c =>
                            // lang=csharp
                            $"builder.AddCommand({c.Type.GetGloballyQualifiedName()}.Descriptor);"
                        )
                    )}}

                    return builder;
                }
            }
            """;
    }
}
