using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CliFx.Generators;

[Generator]
public class ProgramEntryPointGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use the Roslyn compilation API to check whether an entry point already exists.
        // GetEntryPoint() returns null when no valid entry point is found in the compilation,
        // which covers both explicit Main methods and top-level statement programs.
        var needsEntryPoint = context.CompilationProvider.Select(
            static (compilation, cancellationToken) =>
                (
                    compilation.Options.OutputKind == OutputKind.ConsoleApplication
                    || compilation.Options.OutputKind == OutputKind.WindowsApplication
                ) && compilation.GetEntryPoint(cancellationToken) is null
        );

        // Generate a Program entry point for executable projects that don't already have one
        context.RegisterSourceOutput(
            needsEntryPoint,
            static (ctx, needsEntryPoint) =>
            {
                if (!needsEntryPoint)
                    return;

                ctx.AddSource(
                    "AutoGeneratedCommandLineProgram.g.cs",
                    SourceText.From(ProgramEntryPoint.Emit(), Encoding.UTF8)
                );
            }
        );
    }
}
