using System.Text;
using CliFx.Generators.Emitters;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CliFx.Generators;

[Generator]
public class ProgramEntryPointGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var needsEntryPoint = context.CompilationProvider.Select(
            static (compilation, cancellationToken) =>
                (
                    compilation.Options.OutputKind == OutputKind.ConsoleApplication
                    || compilation.Options.OutputKind == OutputKind.WindowsApplication
                ) && compilation.GetEntryPoint(cancellationToken) is null
        );

        context.RegisterSourceOutput(
            needsEntryPoint,
            static (ctx, needsEntryPoint) =>
            {
                if (!needsEntryPoint)
                    return;

                ctx.AddSource(
                    "AutoGeneratedCommandLineProgram.g.cs",
                    SourceText.From(ProgramEntryPoint.Emit(), Encoding.UTF8)
                );
            }
        );
    }
}
