namespace CliFx.Generators;

internal static class ProgramEntryPoint
{
    internal static string Emit()
    {
        // lang=csharp
        return """
            // <auto-generated />
            #nullable enable

            namespace CliFx;

            /// <summary>
            /// Auto-generated entry point for the CliFx-based command-line application.
            /// This class is emitted by the source generator when the project does not define
            /// a <c>Main</c> method or top-level statements.
            /// </summary>
            public static class AutoGeneratedCommandLineProgram
            {
                /// <summary>
                /// Builds and runs the command-line application using all commands detected in the current assembly.
                /// </summary>
                public static async global::System.Threading.Tasks.Task<int> Main() =>
                    await new global::CliFx.CommandLineApplicationBuilder()
                        .AddCommandsFromThisAssembly()
                        .Build()
                        .RunAsync();
            }
            """;
    }
}
