using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CliFx.SourceGeneration.SemanticModel;
using CliFx.SourceGeneration.Utils.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CliFx.SourceGeneration;

/// <summary>
/// Source generator that produces an <c>AddCommandsFromThisAssembly()</c> extension method
/// on <see cref="global::CliFx.CliApplicationBuilder"/> that registers all source-generated
/// command schemas from the current compilation in one call.
/// </summary>
[Generator]
public class AddCommandsFromThisAssemblyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandDeclarations = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                SymbolNames.CliFxCommandAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)ctx.TargetNode;
                    var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

                    if (
                        !classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword)
                        || typeSymbol.IsAbstract
                        || !typeSymbol.ImplementsInterface(SymbolNames.CliFxCommandInterface)
                    )
                        return null;

                    return CommandSchemaGenerator.TryBuildCommandDescriptor(typeSymbol);
                }
            )
            .WhereNotNull();

        context.RegisterSourceOutput(
            commandDeclarations.Collect(),
            static (ctx, commands) => Execute(ctx, commands)
        );
    }

    private static void Execute(
        SourceProductionContext ctx,
        ImmutableArray<CommandDescriptor> commands
    )
    {
        if (commands.IsEmpty)
            return;

        var sb = new StringBuilder();

        sb.Append(
            // lang=csharp
            """
            // <auto-generated/>
            #nullable enable

            namespace CliFx;

            internal static class CliApplicationBuilderExtensions
            {
                internal static global::CliFx.CliApplicationBuilder AddCommandsFromThisAssembly(
                    this global::CliFx.CliApplicationBuilder builder)
                {

            """
        );

        foreach (var command in commands)
        {
            var fqn = command.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.Append(
                // lang=csharp
                $$"""
                        builder.AddCommand({{fqn}}.Schema);

                """
            );
        }

        sb.Append(
            // lang=csharp
            """
                    return builder;
                }
            }

            """
        );

        ctx.AddSource(
            "CliApplicationBuilderExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
