using System.Collections.Immutable;
using System.Text;
using CliFx.SourceGeneration.SemanticModel;
using CliFx.SourceGeneration.Utils.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CliFx.SourceGeneration;

/// <summary>
/// Source generator that produces an <c>AddCommandsFromThisAssembly()</c> extension method
/// on <see cref="global::CliFx.CliApplicationBuilder"/> that registers all source-generated
/// command schemas from the current compilation in one call.
/// </summary>
[Generator]
public class CliApplicationBuilderExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax cls
                    && cls.Modifiers.IndexOf(SyntaxKind.PartialKeyword) >= 0
                    && cls.AttributeLists.Count > 0,
                transform: static (ctx, cancellationToken) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(
                        classDeclaration,
                        cancellationToken
                    );
                    if (symbol is not INamedTypeSymbol typeSymbol)
                        return null;

                    return CommandSchemaGenerator.TryBuildCommandDescriptor(typeSymbol);
                }
            )
            .WhereNotNull();

        context.RegisterSourceOutput(
            commandDeclarations.Collect(),
            static (ctx, commands) => Execute(ctx, commands)
        );
    }

    private static void Execute(
        SourceProductionContext ctx,
        ImmutableArray<CommandDescriptor> commands
    )
    {
        if (commands.IsEmpty)
            return;

        var sb = new StringBuilder();

        sb.Append(
            // lang=csharp
            """
            // <auto-generated/>
            #nullable enable

            namespace CliFx;

            internal static class CliApplicationBuilderExtensions
            {
                internal static global::CliFx.CliApplicationBuilder AddCommandsFromThisAssembly(
                    this global::CliFx.CliApplicationBuilder builder)
                {

            """
        );

        foreach (var command in commands)
        {
            // Commands that already have a Schema member were warned by CommandSchemaGenerator.
            // They don't have a generated Schema property, so skip them here.
            if (command.HasExistingSchemaProperty)
                continue;

            var fqn = command.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.Append(
                // lang=csharp
                $$"""
                        builder.AddCommand({{fqn}}.Schema);

                """
            );
        }

        sb.Append(
            // lang=csharp
            """
                    return builder;
                }
            }

            """
        );

        ctx.AddSource(
            "CliApplicationBuilderExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
