using System.Collections.Generic;
using System.Linq;
using System.Text;
using CliFx.Generators.Utils.Extensions;
using Microsoft.CodeAnalysis;

namespace CliFx.Generators.SemanticModel;

internal sealed class CommandSchemaEmitter(CliFxReferences refs)
{
    internal string GenerateSource(CommandDescriptor command)
    {
        var namespaceName =
            command.Type.Symbol.ContainingNamespace is not null
            && !command.Type.Symbol.ContainingNamespace.IsGlobalNamespace
                ? command.Type.Symbol.ContainingNamespace.ToDisplayString()
                : null;

        var interfaces = new List<string>(2) { refs.IHasHelpOption.ToString() };
        if (command.IsDefault)
            interfaces.Add(refs.IHasVersionOption.ToString());

        var interfaceList =
            interfaces.Count > 0 ? " : " + string.Join(", ", interfaces) : string.Empty;

        var sb = new StringBuilder();

        sb.Append(
            """
            // <auto-generated />

            """
        );

        if (namespaceName is not null)
        {
            sb.Append(
                $$"""
                namespace {{namespaceName}};

                """
            );
        }

        foreach (var containingType in command.Type.Symbol.GetContainingTypes().Reverse())
        {
            sb.AppendLine(
                $"partial class {containingType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}"
            );
            sb.AppendLine("{");
        }

        sb.Append(
            $$"""
            partial class {{command.Type.Name}}{{interfaceList}}
            {
            """
        );

        sb.Append(
            """

                /// <summary>Whether the user requested help (via the -h|--help option).</summary>
                public bool IsHelpRequested { get; set; }

            """
        );

        if (command.IsDefault)
        {
            sb.Append(
                """

                    /// <summary>Whether the user requested version information (via the --version option).</summary>
                    public bool IsVersionRequested { get; set; }

                """
            );
        }

        sb.Append(
            $$"""

                /// <summary>Generated command schema for <see cref="{{command.Type.Name}}"/>.</summary>
                public static {{refs.CommandSchema}} Schema { get; } =
                    new {{refs.CommandSchema}}<{{command.Type.FullyQualifiedName}}>(
                        {{EncodeString(command.Name)}},
                        {{EncodeString(command.Description)}},
                        new {{refs.CommandInputSchema}}[]
                        {
            """
        );

        foreach (var param in command.Parameters.OrderBy(p => p.Order))
            sb.Append(
                // lang=csharp
                $$"""
                            new {{refs.CommandParameterSchema}}<{{command.Type.FullyQualifiedName}}, {{param.Property.Type.FullyQualifiedName}}>(
                                new {{refs.PropertyBinding}}<{{command.Type.FullyQualifiedName}}, {{param.Property.Type.FullyQualifiedName}}>(
                                    "{{param.Property.Name}}",
                                    c => c.{{param.Property.Name}},
                                    (c, v) => c.{{param.Property.Name}} = v),
                                {{param.Order}},
                                {{EncodeString(param.Name)}},
                                {{(param.Property.IsRequired ? "true" : "false")}},
                                {{EncodeString(param.Description)}},
                                {{TryBuildConverterExpr(
                    param.ConverterType,
                    param.Property.Symbol
                )}},
                                {{BuildValidatorsExpr(
                    param.ValidatorTypes,
                    param.Property.Type.FullyQualifiedName
                )}}),

                """
            );

        foreach (var option in command.Options)
            sb.Append(
                // lang=csharp
                $$"""
                            new {{refs.CommandOptionSchema}}<{{command.Type.FullyQualifiedName}}, {{option.Property.Type.FullyQualifiedName}}>(
                                new {{refs.PropertyBinding}}<{{command.Type.FullyQualifiedName}}, {{option.Property.Type.FullyQualifiedName}}>(
                                    "{{option.Property.Name}}",
                                    c => c.{{option.Property.Name}},
                                    (c, v) => c.{{option.Property.Name}} = v),
                                {{EncodeString(option.Name)}},
                                {{(option.ShortName.HasValue ? $"'{option.ShortName}'" : "null")}},
                                {{EncodeString(option.EnvironmentVariable)}},
                                {{(option.Property.IsRequired ? "true" : "false")}},
                                {{EncodeString(option.Description)}},
                                {{TryBuildConverterExpr(
                    option.ConverterType,
                    option.Property.Symbol
                )}},
                                {{BuildValidatorsExpr(
                    option.ValidatorTypes,
                    option.Property.Type.FullyQualifiedName
                )}}),

                """
            );

        sb.Append(
            // lang=csharp
            $$"""
                        new {{refs.CommandOptionSchema}}<{{command.Type.FullyQualifiedName}}, bool>(
                            new {{refs.PropertyBinding}}<{{command.Type.FullyQualifiedName}}, bool>(
                                "IsHelpRequested",
                                c => c.IsHelpRequested,
                                (c, v) => c.IsHelpRequested = v),
                            "help",
                            'h',
                            null,
                            false,
                            "Shows help text.",
                            new {{refs.BoolScalarBindingConverter}}(),
                            global::System.Array.Empty<{{refs.BindingValidator.GlobalBaseFullyQualifiedName}}<bool>>()),

            """
        );

        if (command.IsDefault)
            sb.Append(
                // lang=csharp
                $$"""
                            new {{refs.CommandOptionSchema}}<{{command.Type.FullyQualifiedName}}, bool>(
                                new {{refs.PropertyBinding}}<{{command.Type.FullyQualifiedName}}, bool>(
                                    "IsVersionRequested",
                                    c => c.IsVersionRequested,
                                    (c, v) => c.IsVersionRequested = v),
                                "version",
                                null,
                                null,
                                false,
                                "Shows version information.",
                                new {{refs.BoolScalarBindingConverter}}(),
                                global::System.Array.Empty<{{refs.BindingValidator.GlobalBaseFullyQualifiedName}}<bool>>()),

                """
            );

        sb.Append(
            """
                        });
                }
            """
        );

        foreach (var _ in command.Type.Symbol.GetContainingTypes())
        {
            sb.AppendLine();
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Converter expression builder
    // -------------------------------------------------------------------------

    // Internal so CommandDescriptorBuilder can use it as a null-check to detect
    // properties whose type has no inferrable converter before committing to the descriptor.
    // Returns null if no converter can be inferred (caller must report a diagnostic and skip emission).
    internal string? TryBuildConverterExpr(
        TypeDescriptor? userConverterType,
        IPropertySymbol property
    )
    {
        // User-supplied converter takes precedence and is used as-is.
        if (userConverterType is not null)
            return $"new {userConverterType.GlobalFullyQualifiedName}()";

        var type = property.Type;

        // Sequence types: build a default sequence converter (wrapping a scalar element converter).
        if (
            type.SpecialType != SpecialType.System_String
            && type.TryGetEnumerableUnderlyingType() is { } elementType
        )
            return TryBuildDefaultSequenceConverterExpr(elementType, type);

        // Scalar types: build a default scalar converter (or null for unknown types).
        return TryBuildDefaultScalarConverterExpr(type);
    }

    private string? TryBuildDefaultScalarConverterExpr(ITypeSymbol type)
    {
        var typeFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // string
        if (type.SpecialType == SpecialType.System_String)
            return $"new {refs.StringScalarBindingConverter}()";

        // object
        if (type.SpecialType == SpecialType.System_Object)
            return $"new {refs.ObjectScalarBindingConverter}()";

        // bool
        if (type.SpecialType == SpecialType.System_Boolean)
            return $"new {refs.BoolScalarBindingConverter}()";

        // DateTimeOffset
        if (type is INamedTypeSymbol { ContainingNamespace.Name: "System", Name: "DateTimeOffset" })
            return $"new {refs.DateTimeOffsetScalarBindingConverter}()";

        // DateTime
        if (type is INamedTypeSymbol { ContainingNamespace.Name: "System", Name: "DateTime" })
            return $"new {refs.DateTimeScalarBindingConverter}()";

        // TimeSpan
        if (type is INamedTypeSymbol { ContainingNamespace.Name: "System", Name: "TimeSpan" })
            return $"new {refs.TimeSpanScalarBindingConverter}()";

        // Enum
        if (type.TypeKind == TypeKind.Enum)
            return $"new {refs.EnumScalarBindingConverter.GlobalBaseFullyQualifiedName}<{typeFqn}>()";

        // Nullable<T>
        if (
            type is INamedTypeSymbol { IsValueType: true } named
            && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T
        )
        {
            var innerType = named.TypeArguments[0];
            var innerFqn = innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var innerConverterExpr = TryBuildDefaultScalarConverterExpr(innerType);
            if (innerConverterExpr is null)
                return null;
            return $"new {refs.NullableScalarBindingConverter.GlobalBaseFullyQualifiedName}<{innerFqn}>({innerConverterExpr})";
        }

        // String-parseable with IFormatProvider: static T Parse(string, IFormatProvider)
        var parseMethodWithFormatProvider = type.GetMembers("Parse")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsStatic
                && m.DeclaredAccessibility == Accessibility.Public
                && m.Parameters.Length == 2
                && m.Parameters[0].Type.SpecialType == SpecialType.System_String
                && m.Parameters[1].Type
                    is { ContainingNamespace.Name: "System", Name: "IFormatProvider" }
                && SymbolEqualityComparer.Default.Equals(m.ReturnType, type)
            );

        if (parseMethodWithFormatProvider is not null)
            return $"new {refs.DelegateScalarBindingConverter.GlobalBaseFullyQualifiedName}<{typeFqn}>(s => {typeFqn}.Parse(s!, global::System.Globalization.CultureInfo.InvariantCulture))";

        // String-parseable: static T Parse(string)
        var parseMethod = type.GetMembers("Parse")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsStatic
                && m.DeclaredAccessibility == Accessibility.Public
                && m.Parameters.Length == 1
                && m.Parameters[0].Type.SpecialType == SpecialType.System_String
                && SymbolEqualityComparer.Default.Equals(m.ReturnType, type)
            );

        if (parseMethod is not null)
            return $"new {refs.DelegateScalarBindingConverter.GlobalBaseFullyQualifiedName}<{typeFqn}>(s => {typeFqn}.Parse(s!))";

        // String-constructable: ctor(string)
        if (
            type is INamedTypeSymbol namedConstructable
            && namedConstructable.Constructors.Any(c =>
                c.DeclaredAccessibility == Accessibility.Public
                && c.Parameters.Length == 1
                && c.Parameters[0].Type.SpecialType == SpecialType.System_String
            )
        )
        {
            return $"new {refs.DelegateScalarBindingConverter.GlobalBaseFullyQualifiedName}<{typeFqn}>(s => new {typeFqn}(s!))";
        }

        // IConvertible
        if (
            type.AllInterfaces.Any(i =>
                i.ContainingNamespace?.Name == "System" && i.Name == "IConvertible"
            )
        )
        {
            return $"new {refs.ConvertibleScalarBindingConverter.GlobalBaseFullyQualifiedName}<{typeFqn}>()";
        }

        return null;
    }

    private string? TryBuildDefaultSequenceConverterExpr(
        ITypeSymbol elementType,
        ITypeSymbol collectionType
    )
    {
        var collectionTypeFqn = collectionType.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat
        );
        var elementTypeFqn = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var elementConverterArg = TryBuildDefaultScalarConverterExpr(elementType);
        if (elementConverterArg is null)
            return null;

        // T[]
        if (collectionType is IArrayTypeSymbol)
            return $"new {refs.ArraySequenceBindingConverter.GlobalBaseFullyQualifiedName}<{elementTypeFqn}>({elementConverterArg})";

        // Interface (IReadOnlyList<T>, IEnumerable<T>, etc.)
        if (collectionType.TypeKind == TypeKind.Interface)
            return $"new {refs.ArraySequenceBindingConverter.GlobalBaseFullyQualifiedName}<{elementTypeFqn}, {collectionTypeFqn}>({elementConverterArg})";

        // Concrete type with IEnumerable<T> or T[] constructor (e.g., List<T>)
        if (
            collectionType is INamedTypeSymbol namedCollection
            && namedCollection.Constructors.Any(c =>
                c.DeclaredAccessibility == Accessibility.Public
                && c.Parameters.Length == 1
                && (
                    (
                        c.Parameters[0].Type is IArrayTypeSymbol arrParam
                        && SymbolEqualityComparer.Default.Equals(arrParam.ElementType, elementType)
                    )
                    || (
                        c.Parameters[0].Type is INamedTypeSymbol paramType
                        && paramType.ConstructedFrom.SpecialType
                            == SpecialType.System_Collections_Generic_IEnumerable_T
                        && SymbolEqualityComparer.Default.Equals(
                            paramType.TypeArguments[0],
                            elementType
                        )
                    )
                )
            )
        )
        {
            return $"new {refs.ArrayInitializableSequenceBindingConverter.GlobalBaseFullyQualifiedName}<{elementTypeFqn}, {collectionTypeFqn}>({elementConverterArg}, arr => new {collectionTypeFqn}(arr))";
        }

        return null;
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private string BuildValidatorsExpr(
        IReadOnlyList<TypeDescriptor> validatorTypes,
        string propertyTypeFqn
    )
    {
        var validatorBaseType =
            $"{refs.BindingValidator.GlobalBaseFullyQualifiedName}<{propertyTypeFqn}>";

        if (validatorTypes.Count == 0)
            return $"global::System.Array.Empty<{validatorBaseType}>()";

        var items = string.Join(
            ", ",
            validatorTypes.Select(v => $"new {v.GlobalFullyQualifiedName}()")
        );
        return $"new {validatorBaseType}[] {{ {items} }}";
    }

    // Truly stateless — no refs needed.
    private static string EncodeString(string? value) =>
        value is null ? "null" : $"\"{value.Replace("\\", @"\\").Replace("\"", "\\\"")}\"";
}
