name: CD

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100

    - name: Pack
      run: |
        dotnet pack CliFx.Analyzers --configuration Release
        dotnet pack CliFx --configuration Release

    - name: Deploy
      run: |
        dotnet nuget push CliFx.Analyzers/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push CliFx/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
