name: prerelease

on:
  workflow_dispatch:
    inputs:
      package-version-base:
        type: string
        description: Package version base
        required: true
      package-version-suffix:
        type: string
        description: Package version suffix
        required: true

jobs:
  prerelease:
    uses: Tyrrrz/.github/.github/workflows/nuget.yml@master
    with:
      dotnet-version: 7.0.x
      package-version: ${{ format('{0}-{1}', inputs.package-version-base, inputs.package-version-suffix) }}
      deploy-on-tags-only: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
